apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      command:
        - sleep
      args:
        - 5000
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["NET_ADMIN"]